spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/whatsapp_21Jan26
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cache:
    type: redis
    redis:
      time-to-live: 600000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:tmail7458@gmail.com}
    password: ${MAIL_PASSWORD:zolawlqinwgusalq}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
      port: 35729

  task:
    scheduling:
      enabled: true

google:
  client-id: 33227048330-96tb616sbhubg1nj6n2ploqa2euo8d0o.apps.googleusercontent.com

app:
  encryption:
    secret: zaqwsxcderfvbgtyhnmjuiklop123456 # must match frontend encryptionKey
    enabled: false
